name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch's name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Fix Rollup native dependencies
        run: |
          npm rebuild
          npm install @rollup/rollup-linux-x64-gnu --platform=linux --arch=x64
      - name: Reinstall lightningcss for CI
        run: |
          npm uninstall lightningcss
          npm install lightningcss
      - name: Reinstall TailwindCSS Oxide for CI
        run: |
          npm uninstall @tailwindcss/oxide
          npm install @tailwindcss/oxide
      - name: Build the site
        run: npm run build
        env:
          NODE_ENV: production
          GITHUB_ACTIONS: true
          BUILD_ENVIRONMENT: github-actions
          ENABLE_AI_PROCESSING: false
          SITE_URL: https://gorakudo.org
          SITE_TITLE: GoRakuDo - Komunitas Immersion Bahasa Jepang
          SITE_DESCRIPTION: Komunitas immersion bahasa Jepang terbesar Indonesia
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Discord notification after deployment
  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1.15.3
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@209310690643673088>"
          title: "Deploy to GitHub Pages"
          description: |
            Official Astro deployment completed.
            Triggered by: `${{ github.event_name }}` On Branch: `${{ github.ref_name }}`.
            Environment: GitHub Actions (AI processing disabled for security)
          color: 0x2fa64d
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions Deployer
